### ISSUE TITLE
Can not authrize gitlab-ci

### ISSUE THREAD

**Issue by epiphyllum** [sameersbn/docker-gitlab-ci#22] opened 2015-04-01 03:08 UTC
the whole interaction like this:

## 1  open http://gitlab-ci.tfs.com/
![1](https://cloud.githubusercontent.com/assets/8348065/6933903/1f693fce-d85f-11e4-9307-7e82e995b75b.jpg)

## 2 click login with gitlab; 
![2](https://cloud.githubusercontent.com/assets/8348065/6933914/3a8e0168-d85f-11e4-87dc-03a1c767a54f.jpg)

## 3 click the authorize,  got the error
![3](https://cloud.githubusercontent.com/assets/8348065/6933915/436f7a28-d85f-11e4-8474-761a985ec1bb.jpg)

## my gitlab-ci's log:
```
Started GET "/user_sessions/callback?code=2e0732e88dd59da14b8ca98d399e8697db06ed2db6cbf78de82332264daa27a2" for 127.0.0.1 at 2015-04-01 09:28:14 +0800
Processing by UserSessionsController#callback as HTML
  Parameters: {"code"=>"2e0732e88dd59da14b8ca98d399e8697db06ed2db6cbf78de82332264daa27a2"}
Completed 500 Internal Server Error in 1684ms

OAuth2::Error (<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.7.9</center>
</body>
</html>
):
  app/controllers/user_sessions_controller.rb:18:in `callback'
```

## my gitlab's log
```
Started POST "/oauth/authorize" for 127.0.0.1 at 2015-04-01 09:28:14 +0800
Processing by Oauth::AuthorizationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"VAEcz0lYiCkRvjzMSOW5Ln8deKAdEYsowTAi5/+6FWM=", "client_id"=>"a7d1009834f636acf8ee6c1dd1aa2ebe26b5678a430c3d81f3ff8fb823858fc3", "redirect_uri"=>"http://gitlab-ci.tfs.com/user_sessions/callback", "state"=>"", "response_type"=>"code", "scope"=>"api"}
Redirected to http://gitlab-ci.tfs.com/user_sessions/callback?code=2e0732e88dd59da14b8ca98d399e8697db06ed2db6cbf78de82332264daa27a2
Completed 302 Found in 34ms (ActiveRecord: 23.9ms)
```

**Comment by sameersbn** [comment] 2015-04-01 04:50
duplicate of #18

**Closed by sameersbn** 2015-04-01 04:50 UTC
